from collections import defaultdict
from pathlib import Path

from clients.ollama_client import OllamaClient
from clients.groq_client import GroqClient
from clients.openrouter_client import OpenRouterClient

from config import (
    BOOTSTRAP_DIR,
    MAX_RUNTIME_REPAIRS,
    MAX_TS_REPAIRS,
    MODELS,
    PROMPT_STRATEGIES,
)
from execution.jest_runner import run_jest
from execution.sandbox import (
    append_test_block,
    create_spec_file,
    ensure_append_marker,
    install_temp_spec,
    normalize_content,
    remove_temp_spec,
    validate_generated_block,
)
from execution.typescript_validator import validate_typescript
from metrics.coverage import extract_coverage
from persistence.csv_writer import save_result
from prompts.builder import build_prompt, build_repair_prompt
from prompts.loader import load_functions, load_prompt_template, load_system_prompt
from models.runtime_repair_result import RuntimeRepairResult
from models.method_generated_context import MethodGenerationContext
from models.function_definition import FunctionDefinition
from repair.orchestrator import repair_runtime_failure
from utils.logging import logger


# ─────────────────────────────────────────────────────────────────────────────
# Grouping
# ─────────────────────────────────────────────────────────────────────────────

def group_functions_by_spec(
    functions: list[FunctionDefinition],
) -> dict[str, list[FunctionDefinition]]:
    grouped = defaultdict(list)

    for fn in functions:
        grouped[fn.test_output_file].append(fn)

    for spec_file in grouped:
        grouped[spec_file].sort(key=lambda fn: fn.line)

    return grouped


# ─────────────────────────────────────────────────────────────────────────────
# Bootstrap loading
# The bootstrap spec is generated by ast-cli and written directly into the
# corpus under the test_output_file path. The runner reads it from disk
# instead of calling generate_bootstrap_spec() at runtime.
# ─────────────────────────────────────────────────────────────────────────────

def load_bootstrap_content(test_output_file: str) -> str:
    """
    Reads the bootstrap spec generated by `npx tsx index.ts bootstrap`.
    test_output_file is relative to CORPUS_DIR
    (e.g. "src/patient/patient.service.spec.ts").
    """
    spec_path = BOOTSTRAP_DIR / test_output_file

    if not spec_path.exists():
        raise FileNotFoundError(
            f"Bootstrap spec not found: {spec_path}. "
            "Run `npx tsx index.ts bootstrap` in ast-cli first."
        )

    return spec_path.read_text(encoding="utf-8"), spec_path


# ─────────────────────────────────────────────────────────────────────────────
# TypeScript repair loop
# ─────────────────────────────────────────────────────────────────────────────

def validate_and_repair_typescript(
    *,
    client,
    repair_system_prompt: str,
    generated_spec_path: Path,
) -> bool:
    for ts_attempt in range(1, MAX_TS_REPAIRS + 1):
        logger.info(f"TypeScript validation attempt={ts_attempt}")

        validation = validate_typescript(generated_spec_path)

        if validation.success:
            logger.info("TypeScript validation succeeded")
            return True

        logger.error(
            f"TypeScript validation failed\n"
            f"STDOUT:\n{validation.stdout}\n"
            f"STDERR:\n{validation.stderr}\n"
            f"RETURN CODE: {validation.returncode}"
        )

        current_spec = generated_spec_path.read_text(encoding="utf-8")

        repair_prompt = build_repair_prompt(
            spec_content=current_spec,
            ts_stdout=validation.stdout,
            jest_stderr=validation.stderr,
        )

        logger.info(f"Repairing TypeScript attempt={ts_attempt}")

        repair_response = client.generate(repair_system_prompt, repair_prompt)

        repaired = normalize_content(repair_response.content)
        repaired = ensure_append_marker(repaired)

        generated_spec_path.write_text(repaired, encoding="utf-8")

    logger.error("TypeScript validation failed permanently")
    return False


# ─────────────────────────────────────────────────────────────────────────────
# Runtime repair loop
# ─────────────────────────────────────────────────────────────────────────────

def is_typescript_error(stderr: str) -> bool:
    return "error TS" in stderr


def run_runtime_repair_loop(
    *,
    client,
    repair_system_prompt: str,
    repair_prompt: str,
    generated_spec_path: Path,
    test_output_file: str,
    target_source_file: str,
    method_metadata: MethodGenerationContext,
) -> RuntimeRepairResult:
    jest_result = None
    coverage = {}
    runtime_repairs = 0

    for attempt in range(1, MAX_RUNTIME_REPAIRS + 1):
        logger.info(
            f"Installing temp spec attempt={attempt} {generated_spec_path}"
        )

        temp_spec_path = install_temp_spec(
            generated_file=generated_spec_path,
            relative_output_path=test_output_file,
        )

        try:
            logger.info(f"Running Jest attempt={attempt} for {temp_spec_path}")

            jest_result = run_jest(temp_spec_path, target_source_file)
            coverage = extract_coverage(target_source_file=target_source_file)

            logger.info(
                f"Jest attempt={attempt} success={jest_result.success}"
            )

            if jest_result.stderr:
                logger.debug(jest_result.stderr[:4000])

            ## TODO
            if is_typescript_error(jest_result.stderr):
                logger.error("Runtime loop received TypeScript error")
                return RuntimeRepairResult(
                    success=False,
                    requires_typescript_repair=True,
                    jest_result=jest_result,
                    coverage=coverage,
                    runtime_repairs=runtime_repairs,
                )

            if jest_result.success:
                break

            if attempt < MAX_RUNTIME_REPAIRS:
                runtime_repairs += 1
                logger.info(f"Runtime repair attempt={attempt}")

                repair_count = repair_runtime_failure(
                    runtime_repairs=runtime_repairs,
                    client=client,
                    repair_system_prompt=repair_system_prompt,
                    repair_prompt=repair_prompt,
                    generated_spec_path=generated_spec_path,
                    jest_stderr=jest_result.stderr,
                    method_metadata=method_metadata,
                )

                logger.info(f"attempt={attempt} repair_count={repair_count}")

        finally:
            logger.info(f"Removing temp spec {temp_spec_path}")
            remove_temp_spec(temp_spec_path)

    return RuntimeRepairResult(
        success=jest_result.success if jest_result else False,
        requires_typescript_repair=False,
        jest_result=jest_result,
        coverage=coverage,
        runtime_repairs=runtime_repairs,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Context builder
# ─────────────────────────────────────────────────────────────────────────────

def build_method_generation_context(
    *,
    function_data: FunctionDefinition,
    bootstrap_content: str,
    generated_spec_path: Path,
) -> MethodGenerationContext:
    return MethodGenerationContext(
        method_name=function_data.name,
        source_file=function_data.source_file,
        test_output_file=function_data.test_output_file,
        focused_source=function_data.context.methodSource,
        relevant_dtos=function_data.context.relevantDtos,
        relevant_enums=function_data.context.relevantEnums,
        bootstrap_content=bootstrap_content,
        generated_spec_path=generated_spec_path,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Experiment
# ─────────────────────────────────────────────────────────────────────────────

def run_experiment() -> None:
    functions = load_functions()
    grouped_functions = group_functions_by_spec(functions)

    incremental_system_prompt = load_system_prompt("incremental")
    typescript_repair_system_prompt = load_system_prompt("full_spec_repair")
    runtime_repair_system_prompt = load_system_prompt("repair")

    for model_key, config in MODELS.items():
        provider = config["provider"]
        model_name = config["model"]

        # if provider == "gemini":
        #     client = GeminiClient(model_name)

        if provider == "groq":
            client = GroqClient(model_name)
        
        elif provider == "openrouter":
            client = OpenRouterClient(model_name)

        elif provider == "ollama":
            client = OllamaClient(model_name)

        else:
            raise ValueError(f"Unknown provider: {provider}")

        for strategy in PROMPT_STRATEGIES:
            logger.info(f"Running model={model_key} strategy={strategy}")

            runtime_repair_prompt = load_prompt_template("repair", strategy)

            for test_output_file, file_functions in grouped_functions.items():
                logger.info(f"Generating spec file={test_output_file}")

                try:
                    # ──────────────────────────────────────────────────────
                    # STEP 1 — LOAD BOOTSTRAP
                    # Generated by ast-cli bootstrap command; read from disk.
                    # ──────────────────────────────────────────────────────

                    bootstrap_content, b_generated_spec_path = load_bootstrap_content(test_output_file)

                    generated_spec_path = (
                        create_spec_file(
                            model=model_key,
                            strategy=strategy,
                            test_output_file=test_output_file,
                            content=bootstrap_content,
                        )
                    )

                    context = None  # will be set on last function in loop

                    for function_data in file_functions:
                        logger.info(f"Generating tests function={function_data.name}")

                        try:
                            # ──────────────────────────────────────────────
                            # STEP 2 — BUILD PROMPT
                            # ──────────────────────────────────────────────

                            prompt = build_prompt(
                                strategy=strategy,
                                function_data=function_data,
                                existing_spec_file=b_generated_spec_path,
                            )

                            context = build_method_generation_context(
                                function_data=function_data,
                                bootstrap_content=bootstrap_content,
                                generated_spec_path=generated_spec_path,
                            )

                            # ──────────────────────────────────────────────
                            # STEP 3 — GENERATE
                            # ──────────────────────────────────────────────

                            response = client.generate(
                                incremental_system_prompt,
                                prompt,
                            )

                            logger.debug(
                                f"build prompt response in "
                                f"{response.duration_seconds}s = {response.content}"
                            )

                            # test_block = extract_test_output(response.content)
                            test_block = response.content

                            if test_block is None:
                                logger.warning(
                                    f"test_block is empty"
                                    f"function={function_data.name} "
                                    f"tokens={response.tokens}"
                                )
                                save_result({
                                    "model": model_key,
                                    "strategy": strategy,
                                    "module": function_data.module,
                                    "function": function_data.name,
                                    "ccm": function_data.ccm,
                                    "range": function_data.range,
                                    "duration_seconds": response.duration_seconds,
                                    "tokens": response.tokens,
                                    "generation_success": False,
                                    "error": "test_block_is_empty",
                                })
                                continue

                            if not validate_generated_block(test_block):
                                logger.warning(
                                    f"Invalid block function={function_data.name}"
                                )
                                save_result({
                                    "model": model_key,
                                    "strategy": strategy,
                                    "module": function_data.module,
                                    "function": function_data.name,
                                    "ccm": function_data.ccm,
                                    "range": function_data.range,
                                    "duration_seconds": response.duration_seconds,
                                    "tokens": response.tokens,
                                    "generation_success": False,
                                    "error": "invalid_block",
                                })
                                continue

                            # ──────────────────────────────────────────────
                            # STEP 4 — APPEND
                            # ──────────────────────────────────────────────

                            append_test_block(
                                spec_file=generated_spec_path,
                                content=test_block,
                            )

                            # ──────────────────────────────────────────────
                            # STEP 5 — TS VALIDATION
                            # ──────────────────────────────────────────────

                            # ts_success = validate_and_repair_typescript(
                            #     client=client,
                            #     repair_system_prompt=typescript_repair_system_prompt,
                            #     generated_spec_path=generated_spec_path,
                            # )

                            # if not ts_success:
                            #     logger.error(
                            #         f"TypeScript failed function={function_data.name}"
                            #     )
                            #     save_result({
                            #         "model": model_key,
                            #         "strategy": strategy,
                            #         "function": function_data.name,
                            #          "ccm": function_data.ccm,
                            #         "range": function_data.range,
                            #         "duration_seconds": response.duration_seconds,
                            #         "tokens": response.tokens,
                            #         "generation_success": False,
                            #         "typescript_success": False,
                            #     })
                            #     continue

                            # ──────────────────────────────────────────────
                            # STEP 6 — RUNTIME LOOP
                            # ──────────────────────────────────────────────

                            runtime_result = run_runtime_repair_loop(
                                client=client,
                                repair_system_prompt=runtime_repair_system_prompt,
                                repair_prompt=runtime_repair_prompt,
                                generated_spec_path=generated_spec_path,
                                test_output_file=test_output_file,
                                target_source_file=function_data.source_file,
                                method_metadata=context,
                            )

                            # ──────────────────────────────────────────────
                            # STEP 7 — TS REPAIR FROM RUNTIME (if needed)
                            # ──────────────────────────────────────────────

                            if runtime_result.requires_typescript_repair:
                                ts_success = validate_and_repair_typescript(
                                    client=client,
                                    repair_system_prompt=typescript_repair_system_prompt,
                                    generated_spec_path=generated_spec_path,
                                )

                                if ts_success:
                                    runtime_result = run_runtime_repair_loop(
                                        client=client,
                                        repair_system_prompt=runtime_repair_system_prompt,
                                        repair_prompt=runtime_repair_prompt,
                                        generated_spec_path=generated_spec_path,
                                        test_output_file=test_output_file,
                                        target_source_file=function_data.source_file,
                                        method_metadata=context,
                                    )

                            # ──────────────────────────────────────────────
                            # STEP 8 — SAVE PER-FUNCTION METRICS
                            # ──────────────────────────────────────────────

                            jest_result = runtime_result.jest_result
                            coverage = runtime_result.coverage

                            save_result({
                                "model": model_key,
                                "strategy": strategy,
                                "module": function_data.module,
                                "function": function_data.name,
                                "source_file": function_data.source_file,
                                "test_output_file": function_data.test_output_file,
                                "ccm": function_data.ccm,
                                "range": function_data.range,
                                "duration_seconds": response.duration_seconds,
                                "tokens": response.tokens,
                                "generation_success": True,
                                "jest_success": (
                                    jest_result.success if jest_result else False
                                ),
                                "runtime_repairs": runtime_result.runtime_repairs,
                                "requires_typescript_repair": (
                                    runtime_result.requires_typescript_repair
                                ),
                                **coverage.to_csv_row(),
                            })

                        except Exception as exc:
                            logger.exception(exc)
                            save_result({
                                "model": model_key,
                                "strategy": strategy,
                                "module": function_data.module,
                                "function": function_data.name,
                                "ccm": function_data.ccm,
                                "range": function_data.range,
                                "duration_seconds": response.duration_seconds,
                                "tokens": response.tokens,
                                "fatal_error": str(exc),
                            })

                except Exception as exc:
                    logger.exception(exc)
                    save_result({
                        "model": model_key,
                        "strategy": strategy,
                        "module": function_data.module,
                        "function": function_data.name,
                        "test_output_file": test_output_file,
                        "ccm": function_data.ccm,
                        "range": function_data.range,
                        "duration_seconds": response.duration_seconds,
                        "tokens": response.tokens,
                        "fatal_error": str(exc),
                    })


if __name__ == "__main__":
    run_experiment()
