import json
import subprocess
import tempfile
from pathlib import Path


def patch_test_block(
    *,
    file_path: str,
    test_name: str,
    describe_name: str,
    new_block: str,
) -> None:
    """
    Replaces the it() block identified by test_name, scoped to the
    describe(describe_name) wrapper.

    describe_name should be the fn_id generated by make_fn_id(), e.g.
    "FN_searchOrders_END". Scoping prevents accidental replacement of
    identically-titled it() blocks in other functions' describe wrappers.
    """
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".ts",
        delete=False,
        encoding="utf-8",
    ) as temp:
        temp.write(new_block)
        temp_path = Path(temp.name)

    try:
        result = subprocess.run(
            [
                "cmd",
                "/c",
                "npx",
                "tsx",
                "ts_ast/patch_test_block.ts",
                json.dumps({
                    "file_path":    file_path,
                    "test_name":    test_name,
                    "describe_name": describe_name,
                    "temp_path":    str(temp_path),
                }),
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"Failed to patch test block\n\n"
                f"TEST:        {test_name}\n"
                f"DESCRIBE:    {describe_name}\n"
                f"STDERR:\n{result.stderr}"
            )

    finally:
        if temp_path.exists():
            temp_path.unlink()
