import json
import subprocess


def extract_failed_test_block(
    *,
    file_path: str,
    test_name: str,
    describe_name: str,
) -> str:
    """
    Extracts the it() block identified by test_name, scoped to the
    describe(describe_name) wrapper.

    describe_name should be the fn_id generated by make_fn_id(), e.g.
    "FN_searchOrders_END". Scoping prevents false matches when two
    different functions in the same spec file generate it() blocks
    with identical titles.
    """
    result = subprocess.run(
        [
            "cmd",
            "/c",
            "npx",
            "tsx",
            "ts_ast/extract_test_block.ts",
            json.dumps({
                "file_path":    file_path,
                "test_name":    test_name,
                "describe_name": describe_name,
            }),
        ],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"Failed to extract test block\n\n"
            f"TEST:        {test_name}\n"
            f"DESCRIBE:    {describe_name}\n"
            f"STDOUT:\n{result.stdout}\n"
            f"STDERR:\n{result.stderr}"
        )

    block = result.stdout.strip()

    if not block:
        raise RuntimeError(
            f"Empty extracted block for '{test_name}' "
            f"in describe '{describe_name}'"
        )

    return block
